[versions]
fabric_loom = "1.13-SNAPSHOT"
minotaur = "2.+"

minecraft = "1.21.1"
yarn = "1.21.1+build.3"

fabric_loader = "0.17.3"
fabric_api = "0.116.7+1.21.1"

trainmurdermystery = "1.2.6-1.21.1"
ratatouille = "1.4.1-1.21.1"
cca = "6.1.1"
modmenu = "11.0.3"
voicechat_api = "2.6.0"
voicechat = "fabric-1.21.1-2.6.6"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }

trainmurdermystery = { group = "dev.doctor4t", name = "trainmurdermystery", version.ref = "trainmurdermystery" }
ratatouille = { group = "dev.doctor4t", name = "ratatouille", version.ref = "ratatouille" }

cca_base = { group = "org.ladysnake.cardinal-components-api", name = "cardinal-components-base", version.ref = "cca" }
cca_world = { group = "org.ladysnake.cardinal-components-api", name = "cardinal-components-world", version.ref = "cca" }
cca_entity = { group = "org.ladysnake.cardinal-components-api", name = "cardinal-components-entity", version.ref = "cca" }
cca_scoreboard = { group = "org.ladysnake.cardinal-components-api", name = "cardinal-components-scoreboard", version.ref = "cca" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

voicechat_api = { group = "de.maxhenkel.voicechat", name = "voicechat-api", version.ref = "voicechat_api" }
voicechat = { group = "maven.modrinth", name = "simple-voice-chat", version.ref = "voicechat" }
